/* Generated by Yosys 0.8+316 (git sha1 57c2763f, clang 4.0.1-6 -fPIC -Os) */

module \../and.aig (n1, n2, n3);
  wire _0_;
  wire _1_;
  wire _2_;
  input n1;
  input n2;
  output n3;
  \$_AND_  _3_ (
    .A(_1_),
    .B(_0_),
    .Y(_2_)
  );
  assign _1_ = n2;
  assign _0_ = n1;
  assign n3 = _2_;
endmodule
