/* Generated by Yosys 0.8+316 (git sha1 57c2763f, clang 4.0.1-6 -fPIC -Os) */

module \../halfadder.aig (y, s, c, x);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  output c;
  wire n1_inv;
  wire n2_inv;
  wire n3_inv;
  wire n4;
  wire n4_inv;
  output s;
  input x;
  input y;
  \$_AND_  _4_ (
    .A(_3_),
    .B(_2_),
    .Y(_0_)
  );
  \$_XOR_  _5_ (
    .A(_3_),
    .B(_2_),
    .Y(_1_)
  );
  assign _3_ = y;
  assign _2_ = x;
  assign c = _0_;
  assign s = _1_;
endmodule
