/* Generated by Yosys 0.8+316 (git sha1 57c2763f, clang 4.0.1-6 -fPIC -Os) */

module \../inverter.aig (n1, n1_inv);
  input n1;
  output n1_inv;
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _0_ (
    .A(n1),
    .Y(n1_inv)
  );
endmodule
