/* Generated by Yosys 0.8+316 (git sha1 57c2763f, clang 4.0.1-6 -fPIC -Os) */

module \../inverter.aig (n1, n1_inv);
  wire _0_;
  wire _1_;
  input n1;
  output n1_inv;
  \$_NOT_  _2_ (
    .A(_0_),
    .Y(_1_)
  );
  assign _0_ = n1;
  assign n1_inv = _1_;
endmodule
