/* Generated by Yosys 0.8+316 (git sha1 57c2763f, clang 4.0.1-6 -fPIC -Os) */

module \../toggle.aig (clk, n1, n1_inv);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  input clk;
  output n1;
  output n1_inv;
  \$_DFF_P_  _5_ (
    .C(clk),
    .D(_1_),
    .Q(_2_)
  );
  initial _5_.Q = 1'h0;
  \$_NOT_  _6_ (
    .A(_2_),
    .Y(_4_)
  );
  \$_NOT_  _7_ (
    .A(_2_),
    .Y(_1_)
  );
  assign _3_ = _2_;
  assign n1_inv = _4_;
  assign n1 = _3_;
endmodule
