/* Generated by Yosys 0.8+316 (git sha1 57c2763f, clang 4.0.1-6 -fPIC -Os) */

module \../true.aig (n0_inv);
  wire _0_;
  wire _1_;
  wire n0;
  output n0_inv;
  assign _1_ = 1'h1;
  assign n0_inv = _1_;
endmodule
