/* Generated by Yosys 0.8+316 (git sha1 57c2763f, clang 4.0.1-6 -fPIC -Os) */

module \../notcnt1e.aig (clk, n1);
  input clk;
  input n1;
  wire n1_inv;
  (* init = 32'd0 *)
  reg n2 = 32'd0;
  wire n2_inv;
  wire n3;
  wire n3_inv;
  wire n4;
  wire n4_inv;
  wire n5;
  always @(posedge clk)
      n2 <= n5;
  assign n3 = n2_inv & n1_inv;
  assign n4 = n2 & n1;
  assign n5 = n4_inv & n3_inv;
  assign n1_inv = ~n1;
  assign n2_inv = ~n2;
  assign n3_inv = ~n3;
  assign n4_inv = ~n4;
endmodule
